export {default as IcoDown} from './ico-down.svg';
export {default as IcoLeft} from './ico-left.svg';
export {default as IcoSearch} from './ico-search.svg';
export {default as IcoChat} from './ico-chat.svg';
export {default as IcoUser} from './ico-user.svg';
export {default as IcoHome} from './ico-home.svg';
export {default as IcoPlus} from './ico-plus.svg';
export {default as IcoClose} from './ico-close.svg';
export {default as IcoRight} from './ico-right.svg';
